/*
	Author: Jonathan Bairstow (Bulltech Solutions Ltd)
	Created: 28/05/2018

	Blog Post: https://sql-sith.weebly.com/sql-sith-blog/json-quick-start-guide
	
*/


-- JSON as a variable

	DECLARE @json NVARCHAR(4000)
	SET @json = 
	N'{	
	"teams":[{"name":"Bradford Bulls",
			"Players":[{"number":1, "name":"Lee Smith", "position":"Centre"},
				 {"number":2, "name":"Ethan Ryan", "position":"Winger"} 
				 ]
			},
			{"name":"Keighley Cougars",
			"Players":[{"number":1, "name":"Ritchie Hawkyard", "position":"Fullback"},
				 {"number":2, "name":"Andy Gabriel", "position":"Winger"} 
				 ]
			}]
	}'

	Select	@json as JSON

-- Check that the JSON is valid
	Select ISJSON(@json)

-- Basic Select
	Select	*
	from	OpenJSON(@json)

-- Select with Path - Details of a single player
	​Select *
	from OpenJSON(@json, '$.teams[1].Players[1]')
	

-- Supplying a typed list for fields

	Select name, number, position
	from OpenJSON(@json,'$.teams[1].Players[1]')
	With (
	number int,
	name varchar(50),
	position varchar(50)
	)

-- Renaming Fields
	Select PlayerName, SquadNumber, Position
	from OpenJSON(@json,'$.teams[0].Players[0]')
	With (
	SquadNumber int '$.number',
	PlayerName varchar(50) '$.name',
	Position varchar(50) '$.position'
	)


-- Multiple collections

	​Select TeamName, SquadNumber, PlayerName, position
	from OpenJSON(@json,'$.teams')
	With (
			TeamName varchar(50) '$.name',
			Players NVARCHAR(max) As JSON
	)
	cross apply OpenJSON(Players)
	With (
			SquadNumber int '$.number',
			PlayerName varchar(50) '$.name',
			position varchar(50)
	)


-- From a table 

	Declare @SquadsTable table ( TestJSON varchar(max))

	insert @SquadsTable (TestJSON)
	values (@json)

	Select TeamName, number, PlayerName, position
	from @SquadsTable
	cross apply OpenJSON(TestJSON,'$.teams')
	With (
			TeamName varchar(50) '$.name', 
			Players NVARCHAR(max) As JSON
	)
	cross apply OpenJSON(Players)
	With (
			number int,
			PlayerName varchar(50) '$.name',
			position varchar(50)
	)
	;

-- JSON Arrays
	
	Select	value PlayerName
	FROM OPENJSON(N'{"Players":["Lee Smith", "Ethan Ryan", "Ritchie Hawkyard", "Andy Gabriel"]}','$.Players')  
	
-- Creating JSON

	Create table #Squad
	(
	TeamName		varchar(50),
	SquadNumber	int,
	PlayerName	varchar(50),
	Position		varchar(50)
	)

	insert	#Squad
	values	('Bradford Bulls',1,'Lee Smith','Centre'),
			('Bradford Bulls',2,'Ethan Ryan','Winger'),
			('Keighley Cougars',1,'Ritchie Hawkyard','Fullback'),
			('Keighley Cougars',2,'Andy Gabriel','Winger')

-- Autogenerated JSON Schema

	Select *
	from #Squad
	FOR JSON Auto
	
	/*
	[   { "TeamName": "Bradford Bulls", "SquadNumber": 1, "PlayerName": "Lee Smith", "Position": "Centre" }, 
	    { "TeamName": "Bradford Bulls", "SquadNumber": 2, "PlayerName": "Ethan Ryan", "Position": "Winger" }, 
	    { "TeamName": "Keighley Cougars", "SquadNumber": 1, "PlayerName": "Ritchie Hawkyard", "Position": "Fullback" }, 
	    { "TeamName": "Keighley Cougars", "SquadNumber": 2, "PlayerName": "Andy Gabriel", "Position": "Winger" }
	]	
	*/

-- Definining a root
	
	Select	*
	from	#Squad
	FOR JSON Path, Root('teams')

	/*
	{ "teams": [    { "TeamName": "Bradford Bulls", "SquadNumber": 1, "PlayerName": "Lee Smith", "Position": "Centre" }, 
					{ "TeamName": "Bradford Bulls", "SquadNumber": 2, "PlayerName": "Ethan Ryan", "Position": "Winger" }, 
					{ "TeamName": "Keighley Cougars", "SquadNumber": 1, "PlayerName": "Ritchie Hawkyard", "Position": "Fullback" }, 
					{ "TeamName": "Keighley Cougars", "SquadNumber": 2, "PlayerName": "Andy Gabriel", "Position": "Winger" }
				] 
	}
	*/


-- Defining single sub-objects

	Select	TeamName, SquadNumber 'Player.SquadNumber', PlayerName 'Player.PlayerName', Position 'Player.Position'
	from	#Squad
	FOR JSON Path

	/*
	[   { "TeamName": "Bradford Bulls", "Player": { "SquadNumber": 1, "PlayerName": "Lee Smith", "Position": "Centre" } }, 
	    { "TeamName": "Bradford Bulls", "Player": { "SquadNumber": 2, "PlayerName": "Ethan Ryan", "Position": "Winger" } }, 
	    { "TeamName": "Keighley Cougars", "Player": { "SquadNumber": 1, "PlayerName": "Ritchie Hawkyard", "Position": "Fullback" } }, 
	    { "TeamName": "Keighley Cougars", "Player": { "SquadNumber": 2, "PlayerName": "Andy Gabriel", "Position": "Winger" } }
	]
	*/

-- Creating Grouped objects

	Select	TeamName as 'name',
		(	Select	SquadNumber as 'number',
					PlayerName as 'name',
					Position as 'position'
			from	#Squad p
			where	TeamName = s.TeamName
			for JSON Path
		)Players
	from	(
			Select	distinct  TeamName
			from	#Squad
			) s
	for JSON Path, Root('teams')

	/*
	{ "teams": [{ "name": "Bradford Bulls", 
	              "Players": [  { "number": 1, "name": "Lee Smith", "position": "Centre" }, 
	                            { "number": 2, "name": "Ethan Ryan", "position": "Winger" }
	                        ] 
	            }, 
	            { "name": "Keighley Cougars", 
	              "Players": [  { "number": 1, "name": "Ritchie Hawkyard", "position": "Fullback" }, 
	                            { "number": 2, "name": "Andy Gabriel", "position": "Winger" }
	                        ] 
	            }] 
	}
	*/


